# Generated by Django 5.2.17 on 2026-08-29 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_detallepedido_subtotal_alter_pedido_total_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantiad',
            new_name='cantidad',
        ),
    ]
