# Generated by Django 5.2.17 on 2026-09-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_cantiad_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'pendiente en cocina'), ('entregado', 'Entregado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20),
        ),
    ]
