# Generated by Django 5.2.17 on 2026-09-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hora_entrega',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
